# docker-compose -f docker-compose.yml up -d
# 直接安装
# docker run -d \
#  --name w13scan \
#  -p 7778:7778 \
#  -v ./output:/w13scan/w13scan/output \
#  fuzhengwei/w13scan:1.0 \
#  python3 w13scan.py -s 127.0.0.1:7778 --html
# 如果想让w13scan被动模式支持https，先启动docker w13scan,再配置浏览器代理到 ip:7778 然后在浏览器中访问 http://w13scan.ca 下载证书并信任它。
# 源码：https://github.com/fuzhengwei/w13scan
version: '3.8'
services:
  w13scan:
    image: fuzhengwei/w13scan:1.0
    container_name: w13scan
    ports:
      - "7778:7778"
    volumes:
      - ./output:/w13scan/W13SCAN/output
    entrypoint: ["python3", "w13scan.py", "-s", "0.0.0.0:7778", "--html"]
    tty: true