server:
  port: 8091

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:13306/road_map?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    # SpringBoot 默认配置的连接池 Hikari 可以不用指定，这里指定只是想告诉它是通过哪个数据源实例化的
    type: com.zaxxer.hikari.HikariDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  prometheus:
    enabled: true

# python3 w13scan.py -s 127.0.0.1:8091 --html
# http://127.0.0.1:8091/actuator/heapdump
# http://127.0.0.1:8091/actuator/env

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml